### ISSUE TITLE
检测到在' optimizer.step() '之前调用了' lr_scheduler.step() '。 

### ISSUE THREAD

**Issue by The-Last-Programmer** [JupiterEthan/GCRN-complex#2]
首先，感谢谭可老师分享的代码。我在run的过程中报错，提示是在' optimizer.step() '之前调用了' lr_scheduler.step() '。我检查了models.py里的代码，发现实际上是先使用的optimizer.step()，再用到的scheduler.step()。不知道如何解决这一问题。

**Comment by JupiterEthan** [comment]
Hello, could you post the detailed error messages?
